encrype-hook: remove `resolved` i dont know what it is

diff --git a/encryptedroot/encrypt_hook b/encryptedroot/encrypt_hook
--- a/encryptedroot/encrypt_hook
+++ b/encryptedroot/encrypt_hook
@@ -14,10 +14,9 @@ EOF
         if [ "$ckdev" = "rootfs" ]; then
             ckeyfile=$ckarg1
         else
-
-            while ! resolved=$(resolve_device "${ckdev}" ${rootdelay}); do
-                echo "Waiting for Key Device ${ckdev}($resolved). Press an Enter to continue with password:"
-                if read -t 1 ; then
+            while ! [ -b "${ckdev}" ]; do
+                echo "Waiting for Key Device. Press Enter to continue with password:"
+                if read -t 1 -n 1 ; then
                     ckeyfile=
                     break
                 fi
@@ -28,19 +27,19 @@ EOF
                         # Use a file on the device
                         # ckarg1 is not numeric: ckarg1=filesystem, ckarg2=path
                         mkdir /ckey
-                        mount -r -t "$ckarg1" "$resolved" /ckey
+                        mount -r -t "$ckarg1" "${ckdev}" /ckey
                         dd if="/ckey/$ckarg2" of="$ckeyfile" >/dev/null 2>&1
                         umount /ckey
                         ;;
                     *)
                         # Read raw data from the block device
                         # ckarg1 is numeric: ckarg1=offset, ckarg2=length
-                        dd if="$resolved" of="$ckeyfile" bs=1 skip="$ckarg1" count="$ckarg2" >/dev/null 2>&1
+                        dd if="${ckdev}" of="$ckeyfile" bs=1 skip="$ckarg1" count="$ckarg2" >/dev/null 2>&1
                         ;;
                 esac
             fi
         fi
-        [ ! -f ${ckeyfile} ] && echo "Keyfile could not be opened. Reverting to passphrase." || echo -e "got the Key"
+        [ ! -f "${ckeyfile}" ] && echo "Keyfile could not be opened. Reverting to passphrase." || echo -e "got the Key"
     fi
 
     if [ -n "${cryptdevice}" ]; then
@@ -75,7 +74,7 @@ EOF
             [ ${DEPRECATED_CRYPT} -eq 1 ] && warn_deprecated
             dopassphrase=1
             # If keyfile exists, try to use that
-            if [ -f ${ckeyfile} ]; then
+            if [ -f "${ckeyfile}" ]; then
                 if eval cryptsetup --key-file ${ckeyfile} open --type luks ${resolved} ${cryptname} ${cryptargs} ${CSQUIET}; then
                     dopassphrase=0
                 else
